on:
  push:
    # branches: dev

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
      - run: npm ci
      - run: npm build:all
      - run: npm test:all
      - uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_PUBLISH }}
