name: Publish

on:
  push:
    branches:
      - dev

permissions:
  contents: read

concurrency:
  group: publish-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm ci --include=optional

      - name: Build
        run: npm run build:all

      - name: Lint packages
        run: npm run lint:check:deps

      - name: Lint spark-server
        run: npm run lint:check

      - name: Test
        run: npm run test:all

      - name: Publish @brewskey/spark-protocol
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_PUBLISH }}
          access: public
          package: ./packages/spark-protocol

      - name: Publish @brewskey/spark-server
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_PUBLISH }}
          access: public
